"""create_all_tables

Revision ID: 5486c12caadf
Revises:
Create Date: 2025-10-25 17:24:07.215798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5486c12caadf"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otp",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "otp",
            sa.String(length=4),
            nullable=False,
            comment="One-time password for verification",
        ),
        sa.Column(
            "phone_number",
            sa.String(length=15),
            nullable=False,
            comment="Phone number associated with the OTP",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            nullable=False,
            comment="Expiry time for the OTP",
        ),
        sa.Column(
            "used",
            sa.Boolean(),
            nullable=True,
            comment="Indicates if the OTP has been used",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp when the OTP was created",
        ),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "password_resets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("used", sa.Boolean(), nullable=True),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name="fk_users_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_id"],
            name="fk_users_updated_by",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("phone_number"),
        sa.UniqueConstraint("phone_number", name="uq_users_phone_number"),
        sa.UniqueConstraint("username"),
        sa.UniqueConstraint("username", name="uq_users_username"),
    )
    op.create_index("idx_users_phone_number", "users", ["phone_number"], unique=False)
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_index("idx_users_username", "users", ["username"], unique=False)
    op.create_table(
        "whatsapp_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("webhook_secret", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "areas",
        sa.Column("area_id", sa.UUID(), nullable=False),
        sa.Column("area_name", sa.String(), nullable=False),
        sa.Column("elevation", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name="fk_areas_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_id"],
            name="fk_areas_updated_by",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("area_id"),
        sa.UniqueConstraint("area_name", name="uq_area_name"),
    )
    op.create_table(
        "packages",
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("amperage", sa.Integer(), nullable=False),
        sa.Column("activation_fee", sa.Integer(), nullable=False),
        sa.Column("fixed_fee", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name="fk_packages_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_id"],
            name="fk_packages_updated_by",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("package_id"),
        sa.UniqueConstraint("amperage"),
        sa.UniqueConstraint("amperage", name="uq_amperage"),
    )
    op.create_table(
        "rates",
        sa.Column("rate_id", sa.UUID(), nullable=False),
        sa.Column("coastal_kwh_rate", sa.Integer(), nullable=False),
        sa.Column("mountain_kwh_rate", sa.Integer(), nullable=False),
        sa.Column("fixed_sub_hours", sa.Integer(), nullable=False),
        sa.Column("fixed_sub_rate", sa.Integer(), nullable=False),
        sa.Column("dollar_rate", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name="fk_rates_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_id"],
            name="fk_rates_updated_by",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("rate_id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name="fk_refresh_tokens_user_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("token_id"),
        sa.UniqueConstraint(
            "user_id", "device_id", "token_hash", name="uq_refresh_tokens_user_device"
        ),
    )
    op.create_index(
        "idx_refresh_tokens_device_id", "refresh_tokens", ["device_id"], unique=False
    )
    op.create_index(
        "idx_refresh_tokens_revoked", "refresh_tokens", ["revoked"], unique=False
    )
    op.create_index(
        "idx_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "templates",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name="fk_templates_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_id"],
            name="fk_templates_updated_by",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("template_id"),
        sa.UniqueConstraint("name", name="uq_templates_name"),
    )
    op.create_table(
        "meters",
        sa.Column("meter_id", sa.UUID(), nullable=False),
        sa.Column("customer_full_name", sa.String(length=255), nullable=False),
        sa.Column("customer_phone_number", sa.String(length=20), nullable=False),
        sa.Column("area_id", sa.UUID(), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("initial_reading", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("package_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("blob_name", sa.String(length=500), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["areas.area_id"], name="fk_meters_area_id"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name="fk_meters_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.package_id"], name="fk_meters_package_id"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_id"],
            name="fk_meters_updated_by",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("meter_id"),
        sa.UniqueConstraint(
            "customer_full_name",
            "customer_phone_number",
            "address",
            name="uq_customer_identity_address",
        ),
    )
    op.create_table(
        "bills",
        sa.Column("bill_id", sa.UUID(), nullable=False),
        sa.Column(
            "bill_number",
            sa.Integer(),
            sa.Identity(always=False, start=1),
            nullable=False,
        ),
        sa.Column("meter_id", sa.UUID(), nullable=True),
        sa.Column("amount_due_lbp", sa.Integer(), nullable=False),
        sa.Column("amount_due_usd", sa.Float(), nullable=False),
        sa.Column("total_paid_lbp", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_paid_usd", sa.Float(), server_default="0", nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("blob_name", sa.String(length=255), nullable=True),
        sa.Column("rate_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name="fk_bills_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["meter_id"],
            ["meters.meter_id"],
            name="fk_bills_meter_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rate_id"], ["rates.rate_id"], name="fk_bills_rate_id", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_id"],
            name="fk_bills_updated_by",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("bill_id"),
        sa.UniqueConstraint("bill_number"),
        sa.UniqueConstraint("meter_id", "due_date", name="uq_bill_identity"),
    )
    op.create_index("ix_bills_due_date", "bills", ["due_date"], unique=False)
    op.create_index("ix_bills_status", "bills", ["status"], unique=False)
    op.create_table(
        "fixes",
        sa.Column("fix_id", sa.UUID(), nullable=False),
        sa.Column("meter_id", sa.UUID(), nullable=True),
        sa.Column("fix_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "cost", sa.Numeric(precision=15, scale=2, asdecimal=False), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name="fk_fixes_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["meter_id"],
            ["meters.meter_id"],
            name="fk_fixes_meter_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_id"],
            name="fk_fixes_updated_by",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("fix_id"),
    )
    op.create_index("ix_fixes_fix_date", "fixes", ["fix_date"], unique=False)
    op.create_table(
        "readings",
        sa.Column("reading_id", sa.UUID(), nullable=False),
        sa.Column("meter_id", sa.UUID(), nullable=True),
        sa.Column("reading_date", sa.Date(), nullable=False),
        sa.Column("current_reading", sa.Integer(), nullable=False),
        sa.Column("previous_reading", sa.Integer(), nullable=False),
        sa.Column("usage", sa.Integer(), nullable=False),
        sa.Column("reading_sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("blob_name", sa.String(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name="fk_readings_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["meter_id"],
            ["meters.meter_id"],
            name="fk_readings_meter_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_id"],
            name="fk_readings_updated_by",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("reading_id"),
    )
    op.create_index("ix_readings_meter_id", "readings", ["meter_id"], unique=False)
    op.create_index(
        "ix_readings_reading_date", "readings", ["reading_date"], unique=False
    )
    op.create_index("ix_readings_status", "readings", ["status"], unique=False)
    op.create_table(
        "payments",
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("bill_id", sa.UUID(), nullable=True),
        sa.Column("meter_id", sa.UUID(), nullable=True),
        sa.Column("amount_lbp", sa.Integer(), nullable=False),
        sa.Column("amount_usd", sa.Float(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.bill_id"],
            name="fk_payments_bill_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name="fk_payments_created_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["meter_id"],
            ["meters.meter_id"],
            name="fk_payments_meter_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_id"],
            name="fk_payments_updated_by",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("payment_id"),
    )
    op.create_index("ix_payments_bill_id", "payments", ["bill_id"], unique=False)
    op.create_index("ix_payments_meter_id", "payments", ["meter_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payments_meter_id", table_name="payments")
    op.drop_index("ix_payments_bill_id", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_readings_status", table_name="readings")
    op.drop_index("ix_readings_reading_date", table_name="readings")
    op.drop_index("ix_readings_meter_id", table_name="readings")
    op.drop_table("readings")
    op.drop_index("ix_fixes_fix_date", table_name="fixes")
    op.drop_table("fixes")
    op.drop_index("ix_bills_status", table_name="bills")
    op.drop_index("ix_bills_due_date", table_name="bills")
    op.drop_table("bills")
    op.drop_table("meters")
    op.drop_table("templates")
    op.drop_index("idx_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index("idx_refresh_tokens_revoked", table_name="refresh_tokens")
    op.drop_index("idx_refresh_tokens_device_id", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("rates")
    op.drop_table("packages")
    op.drop_table("areas")
    op.drop_table("whatsapp_session")
    op.drop_index("idx_users_username", table_name="users")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_index("idx_users_phone_number", table_name="users")
    op.drop_table("users")
    op.drop_table("password_resets")
    op.drop_table("otp")
    # ### end Alembic commands ###
